controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

person_new:
    path: /person
    controller: App\Controller\PersonController::new
    methods: ['GET', 'POST']
